37 Adding complaints application
spry-group/trashradar-api pull request #38
Opened 2017-02-23 22:44 UTC by marton987

Please no not merge this PR, I'm just testing coverage

2017-02-24 02:07 UTC, carlosabbate requested changes

2017-02-24 02:07 UTC, carlosabbate commented on trashradar-api/complaints/models.py
> +    twitter = models.CharField(max_length=200)
200 characters for a twitter username is an overkill. On top of that, are we assuming that every entity has a twitter account?

2017-02-24 02:07 UTC, chitty commented on trashradar-api/complaints/models.py
> +    message = models.TextField()
Is the entity every complaint message? Or the organization that should pick up the trash?

I see this as two tables:
- Let's say `entity` with name, twitter, phone, etc.
- And, `message` with content, timestamp, author, location, picture and a FK to the `entity`.

2017-03-10 16:50 UTC, marton987 commented on trashradar-api/complaints/models.py
> +    message = models.TextField()
For the record, this message will be replaced with message_template

2017-03-10 16:59 UTC, carlosabbate approved these changes

2017-03-10 16:59 UTC, merged